apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: test5
spec:
  path: ./bundles/test5/manifests/cluster/staging
  postBuild:
    substitute:
      NGINX_IMAGE_TAG: "1.22"  # {"$imagepolicy": "staging:nginx"}
      TEST_IMAGE_TAG: "1" # Magic comment here
  sourceRef:
    namespace: staging
  targetNamespace: staging
