apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: test3
spec:
  path: ./bundles/test3/manifests/cluster/devlab
  sourceRef:
    namespace: devlab
  targetNamespace: devlab
