resources:
  - ../../bundles/registry/flux/cluster/production
  - ../../bundles/test1/flux/cluster/production
  - ../../bundles/test2/flux/cluster/production
  - ../../bundles/test3/flux/cluster/production
  - ../../bundles/test4/flux/cluster/production
