apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: registry
spec:
  interval: 2m0s
  prune: true
  sourceRef:
    kind: GitRepository
    name: root-gitops-registry
    namespace: flux-system
  timeout: 2m
  validation: client
  wait: true
