apiVersion: v1
data:
  identity: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JRzJBZ0VBTUJBR0J5cUdTTTQ5QWdFR0JTdUJCQUFpQklHZU1JR2JBZ0VCQkRBY0xTMGNOdkdBRHRDQ21odHQKNWp3MFFYVzF4cnh3T3dGRjIzNm1mR1pDN0l1VDhia1FReGhoZ0M5TFBxN0NRMUdoWkFOaUFBUXM3Q05aRHZvdApLMVkvTVZBM0pLeUcvSDg3VHpvU1Z3NTJlOHM3a2dhNTNWM0I2cjRyN2tDMjNxbHNjQ1RKanVHTHR2ZlF5RDNYCkdtRWxONzRmWHlsbVUvRUFkWlE5SElBVVYydllTM25FUG5tMlVtWXpWNmNBU1o2Ull6TC9OdzQ9Ci0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0K
  identity.pub: ZWNkc2Etc2hhMi1uaXN0cDM4NCBBQUFBRTJWalpITmhMWE5vWVRJdGJtbHpkSEF6T0RRQUFBQUlibWx6ZEhBek9EUUFBQUJoQkN6c0kxa08raTByVmo4eFVEY2tySWI4Znp0UE9oSlhEblo3eXp1U0JybmRYY0hxdml2dVFMYmVxV3h3Sk1tTzRZdTI5OURJUGRjYVlTVTN2aDlmS1daVDhRQjFsRDBjZ0JSWGE5aExlY1ErZWJaU1pqTlhwd0JKbnBGak12ODNEZz09Cg==
  known_hosts: Z2l0aHViLmNvbSBlY2RzYS1zaGEyLW5pc3RwMjU2IEFBQUFFMlZqWkhOaExYTm9ZVEl0Ym1semRIQXlOVFlBQUFBSWJtbHpkSEF5TlRZQUFBQkJCRW1LU0VOalFFZXpPbXhrWk15N29wS2d3RkI5bmt0NVlScllNak51RzVOODd1UmdnNkNMcmJvNXdBZFQveTZ2MG1LVjBVMncwV1oyWUIvKytUcG9ja2c9
kind: Secret
metadata:
  name: flux-system
  namespace: staging
type: Opaque
