apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: registry
spec:
  path: ./bundles/registry/manifests/cluster/devlab
  postBuild:
    substitute:
      REGISTRY_IMAGE_TAG: "2.8.3" # {"$imagepolicy": "devlab:registry:tag"}
  sourceRef:
    namespace: devlab
  targetNamespace: devlab
