apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: test5
spec:
  interval: 2m0s
  prune: true
  sourceRef:
    kind: GitRepository
    name: root-gitops-test5
  timeout: 2m
  validation: client
  wait: true
