apiVersion: v1
kind: Service
metadata:
  name: registry-internal
spec:
  ports:
  - port: 5000
    targetPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: registry-external
spec:
  ports:
  - port: 5000
    targetPort: 5000
  type: NodePort
