commonLabels:
  env: devlab
configMapGenerator:
  - name: test4
    behavior: merge
    literals:
      - ENV=devlab
images:
- name: test
  newName: localhost:30007/test
  newTag: "1" # Magic comment here
resources:
- ../../base
