apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: test3
spec:
  path: ./bundles/test3/manifests/cluster/production
  sourceRef:
    namespace: production
  targetNamespace: production
