commonLabels:
  env: production
configMapGenerator:
  - name: test1
    behavior: merge
    literals:
      - ENV=production
images:
- name: test
  newName: localhost:30009/test
resources:
- ../../base
