apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: bad
  #namespace: devlab
  namespace: production
spec:
  exclusionList:
  - ^.*\.sig$
  image: redis
  interval: 1m0s
  provider: generic
