commonLabels:
  env: staging
configMapGenerator:
  - name: test5
    behavior: merge
    literals:
      - ENV=staging
images:
- name: test
  newName: localhost:30008/test
  newTag: ${TEST_IMAGE_TAG}
resources:
- ../../base
