apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: test1
spec:
  path: ./bundles/test1/manifests/cluster/production
  sourceRef:
    namespace: production
  targetNamespace: production
