apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: root-gitops-test1
spec:
  ref:
    tag: 2023-03-16-11-42 # Magic comment here? This is what we'd chagne to promote an image to prod
