namespace: production
resources:
- ../../base
- namespace.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
patches:
- path: flux-kustomization.patch.yaml
- path: gitrepository.patch.yaml
- path: imageupdateautomation.patch.yaml
