apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: test2
spec:
  path: ./bundles/test2/manifests/cluster/staging
  sourceRef:
    namespace: staging
  targetNamespace: staging
