apiVersion: v1
kind: PersistentVolume
metadata:
  name: staging-registry
spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: /Users/hannahgibson/staging-registry
