apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: registry
spec:
  path: ./bundles/registry/manifests/cluster/staging
  postBuild:
    substitute:
      REGISTRY_IMAGE_TAG: "2" # {"$imagepolicy": "staging:registry:tag"}
  sourceRef:
    namespace: staging
  targetNamespace: staging
