apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: registry
spec:
  path: ./bundles/registry/manifests/cluster/staging
  sourceRef:
    namespace: staging
  targetNamespace: staging
