apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: test1
spec:
  path: ./bundles/test1/manifests/cluster/devlab
  sourceRef:
    namespace: devlab
  targetNamespace: devlab
