apiVersion: apps/v1
kind: Deployment
metadata:
  name: test5
spec:
  template:
    spec:
      containers:
        - envFrom:
          - configMapRef:
              name: test5
          image: test
          name: test
          ports:
          - containerPort: 5000
            name: test
        - name: nginx
          image: nginx
          ports:
          - containerPort: 80
            protocol: TCP
