apiVersion: apps/v1
kind: Deployment
metadata:
  name: registry
spec:
  template:
    spec:
      containers:
        - name: registry
          volumeMounts:
          - name: registry
            mountPath: "/var/lib/registry"
      volumes:
        - name: registry
          persistentVolumeClaim:
            claimName: production-registry
