apiVersion: v1
kind: PersistentVolume
metadata:
  name: production-registry
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: /Users/hannahgibson/production-registry
  storageClassName: hostpath
